#!/bin/bash

current=`pwd`
src="${HOME}/Pictures"
dest="${current}/assets/images/"

#images=`find ${src} -name "*.png" -mtime -1`
images=`find ${src} -name "*.png"`

mkdir -p ${dest}

if [ 0 -ne ${#images} ]
then

	cp -t ${dest} ${images}

	for img in ${images}
	do
		convert -resize "580>" ${img} ${dest}${img##*/}
	done
else
	echo 'nothing to process.'
fi


